### ISSUE TITLE
LR.py - features attribute

### ISSUE THREAD

**Issue by jhoh10** [rk2900/deep-conv-attr#1]
I am having a hard time figuring out how to set a value for self.features. By default in the code it is 5867.  Is there a way this could be automated in the graph building based on the input, or at least a method to calculate what this value should be to avoid index out of bound error?

**Comment by jhoh10** [comment]
Also, any tips on modifying the input data to reduce the number of features required? Much appreciated!

**Comment by Arthur-Null** [comment]
Are you trying to fit the model to a new dataset? You can change the number of features according to the data you use. However, if you need to use data aside from what we provided, you may need to rewrite the training function.

**Comment by jhoh10** [comment]
Yes. I've done my best to to format a new dataset to the same format as your Criteo input definition. (http://apex.sjtu.edu.cn/datasets/13). See example lines below from my dataset. I've gotten the model to work.

One challenge has been that every single visit in the dataset is resulting in a click. So all the rows will have a click value of '1'.
Unfortunately, while the ARNN.py training works, it is not learning on the test set. The train AUC goes up and the log loss decreases, however, the test set AUC is below 0.5 and the loss is flat.

Any thoughts on what could be going wrong? Much appreciated!

Example from dataset:
2 0
1004387 1 1 4 17 0 2 0 0 1
2107159 1 4 2 7 0 2 0 0 1
2 1
1445629 1 2 10 7 0 1 0 1 1
2028937 1 1 17 3 0 1 0 1 1
3 0
1027974 1 1 8 4 0 1 0 3 0
1138274 1 5 1 0 1 1 0 3 0
1711731 1 5 2 23 0 1 1 3 0
3 0
1264264 1 1 1 0 1 2 0 0 0
1264341 1 1 1 0 1 2 0 0 0
1264761 1 1 1 0 1 2 0 0 0
4 0
1291682 1 1 1 0 1 2 0 0 0
1299538 1 1 1 0 1 2 1 0 0
1301782 1 1 1 0 1 2 1 0 0
1318546 1 1 1 0 1 2 1 0 0

**Comment by jhoh10** [comment]
I had formatted the timestamp field as absolute time in seconds from 1970. After scaling the time from 0 (earliest timestamp) to 1 (latest timestamp), the model was able to converge in training.
